// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDioVcyZP86pkjJnt9AGgJ5YId-FiGawc8',
    appId: '1:403146150884:web:9209d28e97fbd116e52df1',
    messagingSenderId: '403146150884',
    projectId: 'naarea-natal',
    authDomain: 'naarea-natal.firebaseapp.com',
    storageBucket: 'naarea-natal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiUQDhU-6lWRnXYC1ofI_bgMxpvy8CIKw',
    appId: '1:403146150884:android:4a0257c59c41f552e52df1',
    messagingSenderId: '403146150884',
    projectId: 'naarea-natal',
    storageBucket: 'naarea-natal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrIqSkwqc1uUb8xfFRW6SVPchPKAcMtB8',
    appId: '1:403146150884:ios:f6d567e0835bf41ce52df1',
    messagingSenderId: '403146150884',
    projectId: 'naarea-natal',
    storageBucket: 'naarea-natal.firebasestorage.app',
    iosBundleId: 'br.naarea.naarea',
  );
}
